// Spanish text configuration
// Centralized for easy translation management
// ALL user-facing text must go here — no hardcoded strings in pages
export const ES = {
  // App
  app: {
    name: 'Salon Pro',
    tagline: 'Gestión de Salón',
    redirecting: 'Redirigiendo...',
    contactAdmin: 'Contacte al administrador para obtener acceso.',
    accessDenied: 'Acceso denegado.',
    adminOnly: 'Solo administradores pueden acceder a esta sección.',
    searchPlaceholder: 'Buscar...',
    noResults: 'Sin resultados',
    selectDate: 'Seleccionar Fecha',
    period: 'Período',
    activate: 'Activar',
    deactivate: 'Desactivar',
  },

  // Auth
  auth: {
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    createAccount: 'Crear Cuenta',
    email: 'Correo',
    password: 'Contraseña',
    firstName: 'Nombre',
    lastName: 'Apellido',
    salonName: 'Nombre del Salón',
    phone: 'Teléfono',
    logout: 'Cerrar Sesión',
    signInSuccess: '¡Sesión iniciada!',
    createAccountSuccess: '¡Cuenta creada!',
    loginFailed: 'Fallo al iniciar sesión',
    invalidCredentials: 'Email o contraseña incorrectos. Intente de nuevo.',
    registerFailed: 'Fallo al registrarse',
  },

  // Navigation
  nav: {
    dashboard: 'Panel',
    sessions: 'Trabajos',
    appointments: 'Citas',
    clients: 'Clientes',
    services: 'Servicios',
    staff: 'Personal',
    inventory: 'Inventario',
    reports: 'Reportes',
    settings: 'Configuración',
    myWork: 'Mis Trabajos',
    myEarnings: 'Mis Ganancias',
    myAppointments: 'Mis Reservas',
    groupDaily: 'Operaciones',
    groupManage: 'Gestión',
    groupSystem: 'Sistema',
    groupMyArea: 'Mi Área',
  },

  // Dashboard
  dashboard: {
    title: 'Panel',
    welcome: 'Bienvenido',
    totalRevenue: 'Ingresos Totales',
    sessions: 'Trabajos',
    clients: 'Clientes',
    avgTransaction: 'Transacción Promedio',
    todaySessions: 'Trabajos de Hoy',
    topServices: 'Servicios Principales',
    topStaff: 'Personal Principal',
    myEarnings: 'Mis Ganancias',
    earningsToday: 'Ganancias Hoy',
    servicesCompleted: 'Servicios Completados',
    sessionsCount: 'trabajos',
    noSessions: 'Sin trabajos hoy',
    noTopServices: 'Sin datos de servicios',
    noTopStaff: 'Sin datos de personal',
    dailyClose: 'Cierre de Caja',
    dailyCloseSubtitle: 'Resumen de cobros del día',
    totalCash: 'Efectivo',
    totalCard: 'Tarjeta',
    totalQR: 'QR',
    totalTransfer: 'Transferencia',
    totalCollected: 'Total Cobrado',
    pendingCollection: 'Pendiente de Cobro',
    activeSessions: 'Trabajos Activos',
    materialsConsumed: 'Costo Materiales',
    materialsSold: 'Materiales Vendidos',
  },

  // Sessions (Trabajos)
  sessions: {
    title: 'Trabajos',
    new: '+ Nuevo Trabajo',
    create: 'Crear Trabajo',
    active: 'Activo',
    completed: 'Completado',
    cancelled: 'Cancelado',
    startTime: 'Hora de Inicio',
    endTime: 'Hora de Fin',
    client: 'Cliente',
    selectClient: 'Seleccionar Cliente',
    totalAmount: 'Monto Total',
    tax: 'Impuesto',
    addService: 'Agregar Servicio',
    closeSession: 'Cerrar Trabajo',
    noActiveSessions: 'Sin trabajos activos',
    noActiveSessionsCta: 'Toque + Nuevo Trabajo para comenzar',
    selectService: 'Seleccionar Servicio',
    selectStaff: 'Asignar Personal',
    services: 'Servicios',
    serviceAdded: 'Servicio agregado',
    sessionClosed: 'Trabajo cerrado',
    sessionCreated: 'Trabajo creado',
    discount: 'Descuento',
    notes: 'Notas',
    status: 'Estado',
    noServices: 'Sin servicios agregados',
    pendingService: 'Pendiente',
    inProgressService: 'En Progreso',
    completedService: 'Completado',
    tapToStart: 'Toca para iniciar',
    tapToComplete: 'Toca para completar',
    customPrice: 'Precio',
    materialsUsed: 'Materiales Utilizados',
    addMaterial: '+ Agregar Material',
    materialCost: 'Costo Material',
    quantity: 'Cantidad',
    commissionLabel: 'Comisión',
    commissionBreakdown: 'Comisión: 50% servicio - material',
    noMaterials: 'Sin materiales',
    removeMaterial: 'Quitar',
    serviceTime: 'Hora',
    viewClientHistory: 'Ver Historial',
    clientHistory: 'Historial del Cliente',
    noHistory: 'Sin historial de servicios',
    materialSellPrice: 'P. Venta',
    servicesSubtotal: 'Servicios',
    materialsSubtotal: 'Materiales',
    materialsInternal: 'Materiales (costo interno)',
    cancelSession: 'Anular Trabajo',
    cancelReason: 'Motivo de Anulación',
    cancelReasonPlaceholder: 'Ej: Error de captura, cliente canceló...',
    sessionCancelled: 'Trabajo anulado',
    cancelledSessions: 'Anulados',
    removeService: 'Quitar Servicio',
    serviceRemoved: 'Servicio quitado',
    confirmClose: '¿Cerrar este trabajo? Se marcará como completado.',
    confirmCancel: '¿Anular este trabajo? Se restaurará el inventario y se anularán los pagos. Esta acción no se puede deshacer.',
    confirmRemoveService: '¿Quitar este servicio? Se restaurará el inventario utilizado.',
    cancelReasonRequired: 'Debe indicar el motivo de anulación',
    stockRestored: 'Inventario restaurado',
    paymentsVoided: 'Pagos anulados',
    reopenSession: 'Reabrir Trabajo',
    sessionReopened: 'Trabajo reabierto',
    confirmReopen: '¿Reabrir este trabajo? Volverá al estado activo.',
    editClosed: 'Editar',
    editClosedNote: 'Agregar correcciones a trabajo cerrado',
    addNote: 'Agregar Nota',
    noteSaved: 'Nota guardada',
    noteLabel: 'Nota / Corrección',
    notePlaceholder: 'Ej: Se olvidó registrar tinte, ajuste de precio...',
  },

  // Appointments
  appointments: {
    title: 'Citas',
    new: '+ Nueva Cita',
    create: 'Crear Cita',
    confirm: 'Confirmar',
    cancel: 'Cancelar Cita',
    pending: 'Pendiente',
    confirmed: 'Confirmada',
    noShow: 'No Se Presentó',
    cancelled: 'Cancelada',
    filterByDate: 'Filtrar por Fecha',
    forDate: 'Citas para',
    noAppointments: 'Sin citas programadas',
    selectClient: 'Seleccionar Cliente',
    selectServices: 'Seleccionar Servicios',
    selectStaff: 'Seleccionar Personal',
    startTime: 'Hora de Inicio',
    endTime: 'Hora de Fin',
    created: '¡Cita creada!',
    updated: '¡Cita actualizada!',
    editTitle: 'Editar Cita',
    confirmed2: '¡Cita confirmada!',
    createFailed: 'Error al crear cita',
    confirmFailed: 'Error al confirmar cita',
    date: 'Fecha',
    time: 'Hora',
    convertToWork: 'Iniciar Trabajo',
    converted: '¡Cita convertida a trabajo!',
    convertFailed: 'Error al convertir cita',
    staffDoubleBooked: 'El personal ya tiene una cita en ese horario',
    cancelTitle: 'Cancelar Cita',
    cancelFailed: 'Error al cancelar cita',
    confirmCancel: '¿Cancelar esta cita? El cliente será notificado.',
  },

  // Services
  services: {
    title: 'Servicios',
    add: '+ Agregar Servicio',
    name: 'Nombre',
    category: 'Categoría',
    price: 'Precio',
    duration: 'Duración (min)',
    description: 'Descripción',
    haircut: 'Corte',
    coloring: 'Coloración',
    styling: 'Peinado',
    nails: 'Uñas',
    waxing: 'Depilación',
    skincare: 'Cuidado de la Piel',
    massage: 'Masaje',
    other: 'Otro',
    noServices: 'Sin servicios',
    editService: 'Editar Servicio',
    deleteConfirm: '¿Eliminar este servicio?',
    updated: 'Servicio actualizado',
    deleted: 'Servicio eliminado',
  },

  // Staff
  staff: {
    title: 'Personal',
    add: '+ Agregar Personal',
    name: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo',
    phone: 'Teléfono',
    role: 'Rol',
    specialty: 'Especialidad',
    stylist: 'Estilista',
    colorist: 'Colorista',
    nailTech: 'Manicurista',
    aesthetician: 'Esteticista',
    barber: 'Barbero/a',
    masseur: 'Masajista',
    assistant: 'Asistente',
    multiService: 'Multi-servicio',
    commission: 'Comisión',
    percentage: 'Porcentaje',
    fixed: 'Fijo',
    skills: 'Habilidades',
    availability: 'Disponibilidad',
    available: 'Disponible',
    notAvailable: 'No Disponible',
    teamMembers: 'Miembros del Equipo',
    noStaff: 'Sin personal',
    editStaff: 'Editar Personal',
    deleteConfirm: '¿Eliminar este miembro del equipo?',
    updated: 'Personal actualizado',
    deleted: 'Personal eliminado',
    cannotDeleteHasWork: 'No se puede eliminar: tiene trabajos registrados',
    earnings: 'Ganancias',
    totalEarnings: 'Ganancias Totales',
    servicesOffered: 'Servicios que Realiza',
    addServicesFirst: 'Primero agrega servicios en la sección de Servicios',
    busy: '⏳ Ocupado/a',
    myWork: 'Mis Trabajos',
    myWorkToday: 'Mis Trabajos de Hoy',
    noMyWork: 'Sin trabajos asignados hoy',
    selfAssign: 'Tomar Trabajo',
    assignedToMe: 'Asignado a mí',
    addMyMaterial: '+ Material',
    unassignedServices: 'Servicios sin asignar',
    availableWorks: 'Trabajos Disponibles',
    myActiveServices: 'Mis Servicios Activos',
    myCompletedToday: 'Completados Hoy',
    materialAdded: 'Material registrado',
    newWork: '+ Nuevo Trabajo',
    createWork: 'Crear Trabajo',
    tabWorks: 'Trabajos',
    tabEarnings: 'Ganancias',
    tabAppointments: 'Reservas',
    myCommissionToday: 'Comisión del día',
    myRevenueToday: 'Mis Ingresos del Día',
    noEarningsToday: 'Sin servicios completados hoy',
    noAppointmentsToday: 'Sin reservas para hoy',
    advancePending: 'Iniciar',
    advanceInProgress: 'Completar',
    statusPending: 'Pendiente',
    statusInProgress: 'En Progreso',
    statusCompleted: 'Completado',
    walkInClient: 'Sin Cliente (Eventual)',
    serviceStatusUpdated: 'Estado actualizado',
    selectService: 'Seleccionar Servicio',
    createAndAssign: 'Crear y Asignarme',
  },

  // Inventory
  inventory: {
    title: 'Inventario',
    add: '+ Agregar Producto',
    name: 'Producto',
    sku: 'SKU',
    category: 'Categoría',
    stock: 'Stock',
    currentStock: 'Stock Actual',
    minStock: 'Stock Mínimo',
    maxStock: 'Stock Máximo',
    cost: 'Costo',
    price: 'Precio',
    lowStock: 'Stock Bajo',
    products: 'Productos',
    allProducts: 'Todos los Productos',
    noProducts: 'Sin productos',
    type: 'Tipo',
    unit: 'Unidad',
    editProduct: 'Editar Producto',
    deleteConfirm: '¿Eliminar este producto?',
    updated: 'Producto actualizado',
    deleted: 'Producto eliminado',
    costPerUnit: 'Costo por Unidad',
    sellingPrice: 'Precio de Venta',
    // Categories
    catHairProducts: 'Productos Capilares',
    catSkincare: 'Cuidado de Piel',
    catWax: 'Cera',
    catNailProducts: 'Productos de Uñas',
    catTools: 'Herramientas',
    catSupplies: 'Suministros',
    catOther: 'Otro',
    // Types
    typeUnit: 'Por Unidad',
    typeMeasurable: 'Medible (ml/g)',
    typeServiceCost: 'Costo de Servicio',
    // Units
    unitPieces: 'Piezas',
    unitMl: 'Mililitros',
    unitG: 'Gramos',
    unitBottles: 'Botellas',
    unitSachets: 'Sobres',
  },

  // Reports
  reports: {
    title: 'Reportes y Analítica',
    serviceProfitability: 'Rentabilidad por Servicio',
    staffPerformance: 'Desempeño del Personal',
    materialCost: 'Costo de Materiales',
    profit: 'Ganancia',
    profitMargin: 'Margen de Ganancia',
    startDate: 'Fecha de Inicio',
    endDate: 'Fecha de Fin',
    applyFilter: 'Aplicar Filtro',
    totalRevenue: 'Ingresos Totales',
    totalMaterialCost: 'Costo Total de Materiales',
    totalProfit: 'Ganancia Total',
    avgProfitMargin: 'Margen Promedio',
    totalStaffEarnings: 'Ganancias del Personal',
    service: 'Servicio',
    sessionsCount: 'Trabajos',
    revenue: 'Ingresos',
    margin: 'Margen %',
    staffMember: 'Personal',
    servicesCount: 'Servicios',
    noData: 'Sin datos para el período seleccionado',
    noStaffData: 'Sin datos de desempeño del personal',
    // Payroll report
    payroll: 'Nómina del Personal',
    payrollSubtitle: 'Detalle de comisiones por período',
    commissionRate: 'Tasa Comisión',
    serviceRevenue: 'Ingresos por Servicios',
    materialDeduction: 'Deducción Materiales',
    commissionEarned: 'Comisión Ganada',
    totalToPay: 'Total a Pagar',
    servicesDetail: 'Detalle de Servicios',
    date: 'Fecha',
    client: 'Cliente',
    price: 'Precio',
    materials: 'Materiales',
    commission: 'Comisión',
    totalPayroll: 'Nómina Total',
    salonProfit: 'Ganancia del Salón',
    noPayrollData: 'Sin datos de nómina para el período seleccionado',
    expandDetail: 'Ver Detalle',
    collapseDetail: 'Ocultar Detalle',
    print: 'Imprimir',
    exportCSV: 'Exportar CSV',
    registerPayment: 'Registrar Pago',
    registerPaymentConfirm: '¿Confirmar que se realizó el pago a este trabajador?',
    paymentRegistered: 'Pago registrado en gastos.',
    paid: 'Pagado',
    payrollPayment: 'Pago de nómina',
  },

  // Clients
  clients: {
    title: 'Clientes',
    add: '+ Agregar Cliente',
    addQuick: '+ Nuevo Cliente',
    quickAddTitle: 'Nuevo Cliente Rápido',
    clientCreated: '¡Cliente creado!',
    name: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo',
    phone: 'Teléfono',
    dateOfBirth: 'Fecha de Nacimiento',
    notes: 'Notas',
    notesPlaceholder: 'Alergias, preferencias, etc.',
    totalSpent: 'Total Gastado',
    lastVisit: 'Última Visita',
    noClients: 'Sin clientes',
    editClient: 'Editar Cliente',
    deleteConfirm: '¿Eliminar este cliente?',
    updated: 'Cliente actualizado',
    deleted: 'Cliente eliminado',
    emailOptional: 'Correo (opcional)',
    phoneOptional: 'Teléfono (opcional)',
    totalSessions: 'Total Trabajos',
    phoneExists: 'Ya existe un cliente con ese número de teléfono',
    walkIn: 'Cliente sin registro',
    deleteBlockedHasSessions: 'No se puede eliminar: este cliente tiene trabajos registrados.',
    search: 'Buscar por nombre o teléfono...',
    viewHistory: 'Ver Historial',
    redeemPoints: 'Puntos / Canjear',
  },

  // Actions
  actions: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    view: 'Ver',
    close: 'Cerrar',
    submit: 'Enviar',
    apply: 'Aplicar',
    yes: 'Sí',
    no: 'No',
    loading: 'Cargando...',
    success: '¡Éxito!',
    error: 'Error',
    warning: 'Advertencia',
    confirm: 'Confirmar',
    add: 'Agregar',
    create: 'Crear',
    update: 'Actualizar',
    search: 'Buscar',
    back: 'Volver',
  },

  // Messages
  messages: {
    fillRequiredFields: 'Por favor complete los campos requeridos',
    operationSuccess: 'Operación exitosa',
    operationFailed: 'Operación fallida',
    confirmDelete: '¿Está seguro de que desea eliminar?',
    noDataFound: 'Sin datos encontrados',
    loadingData: 'Cargando datos...',
    savedSuccessfully: 'Guardado exitosamente',
    deletedSuccessfully: 'Eliminado exitosamente',
    errorOccurred: 'Ocurrió un error',
  },

  // User Management
  users: {
    title: 'Gestión de Usuarios',
    add: '+ Crear Usuario',
    name: 'Nombre',
    email: 'Correo',
    role: 'Rol',
    status: 'Estado',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    selectRole: 'Seleccionar Rol',
    createSuccess: '¡Usuario creado exitosamente!',
    createFailed: 'Error al crear usuario',
    deleteSuccess: 'Usuario eliminado',
    noUsers: 'Sin usuarios registrados',
    passwordMismatch: 'Las contraseñas no coinciden',
    passwordMinLength: 'La contraseña debe tener al menos 6 caracteres',
    accessDeniedUsers: 'Acceso denegado. Solo administradores pueden gestionar usuarios.',
    roleDescAdmin: 'Acceso total',
    roleDescManager: 'Sesiones y Pagos',
    roleDescStaff: 'Solo sus sesiones',
  },

  // Roles
  roles: {
    admin: 'Administrador',
    manager: 'Gerente',
    staff: 'Personal',
    client: 'Cliente',
  },

  // Status
  status: {
    pending: 'Pendiente',
    inProgress: 'En Progreso',
    completed: 'Completado',
    active: 'Activo',
    inactive: 'Inactivo',
    confirmed: 'Confirmado',
    cancelled: 'Cancelado',
  },

  // Material Usage
  material: {
    logUsage: 'Registrar Uso de Material',
    product: 'Producto',
    quantity: 'Cantidad',
    recorded: 'Material registrado',
  },

  // Payments
  payments: {
    processPayment: 'Procesar Pago',
    amount: 'Monto',
    method: 'Método',
    cash: 'Efectivo',
    card: 'Tarjeta',
    qrCode: 'Código QR',
    transfer: 'Transferencia',
    paymentProcessed: 'Pago procesado',
    total: 'Total',
    paid: 'Pagado',
    remaining: 'Restante',
    amountGiven: 'Monto Recibido',
    change: 'Cambio',
    addPayment: '+ Agregar Pago',
    paymentSummary: 'Resumen de Pagos',
    payerNote: 'Nota (quién paga)',
    payerNotePlaceholder: 'Ej: Papá, amiga...',
    splitPayment: 'Pago Dividido',
    advancedOptions: 'Opciones avanzadas',
    fullPayment: 'Pago Completo',
    paymentAdded: 'Pago agregado',
    pendingPayments: 'Pagos Pendientes',
    confirmPayments: 'Confirmar Pagos',
    selectServices: 'Seleccionar servicios a pagar',
    allServices: 'Todos los servicios',
    selectedServices: 'Servicios seleccionados',
    advancePayment: 'Anticipo',
    addCredit: 'Agregar Saldo',
    creditBalance: 'Saldo a Favor',
    applyCredit: 'Usar Saldo',
    creditApplied: 'Saldo aplicado',
    creditAdded: 'Saldo agregado al cliente',
    creditAmount: 'Monto del anticipo',
  },

  // Receipt
  receipt: {
    title: 'Recibo',
    print: 'Imprimir Recibo',
    share: 'Compartir',
    shareWhatsApp: 'WhatsApp',
    date: 'Fecha',
    paymentDetail: 'Detalle de Pagos',
    thankYou: 'Gracias por su preferencia',
    viewReceipt: 'Ver Recibo',
  },

  // Birthday & Loyalty
  birthday: {
    todayBirthdays: 'Cumpleanos Hoy',
    weekBirthdays: 'Cumpleanos Esta Semana',
    noBirthdays: 'Sin cumpleanos esta semana',
    happyBirthday: 'Feliz cumpleanos',
    loyalClient: 'Cliente Frecuente',
    visits: 'visitas',
    newClient: 'Nuevo',
    regular: 'Regular',
    frequent: 'Frecuente',
    vip: 'VIP',
  },

  // Frequent Client
  frequentClient: {
    usualServices: 'Servicios Habituales',
    suggestedService: 'Servicio sugerido',
    basedOnHistory: 'Basado en historial del cliente',
    addSuggested: 'Agregar',
  },

  // Low Stock Alerts
  stockAlert: {
    title: 'Alertas de Inventario',
    outOfStock: 'Agotado',
    lowStock: 'Stock Bajo',
    productsLow: 'productos con stock bajo',
    restockNeeded: 'Reabastecimiento necesario',
    currentStock: 'Actual',
    minStock: 'Minimo',
  },

  // Multi-location / Salons
  salons: {
    title: 'Sucursales',
    add: '+ Nueva Sucursal',
    name: 'Nombre',
    address: 'Direccion',
    city: 'Ciudad',
    phone: 'Telefono',
    email: 'Correo',
    switchSalon: 'Cambiar Sucursal',
    currentSalon: 'Sucursal Actual',
    noSalons: 'Sin sucursales registradas',
    created: 'Sucursal creada',
    updated: 'Sucursal actualizada',
    deleted: 'Sucursal eliminada',
    editSalon: 'Editar Sucursal',
    deleteConfirm: 'Eliminar esta sucursal?',
    manageSalons: 'Gestionar Sucursales',
  },

  // Retail Product Sales
  retail: {
    title: 'Venta de Productos',
    new: '+ Nueva Venta',
    create: 'Registrar Venta',
    product: 'Producto',
    quantity: 'Cantidad',
    unitPrice: 'Precio Unitario',
    total: 'Total',
    addItem: '+ Agregar Producto',
    removeItem: 'Quitar',
    selectClient: 'Cliente (opcional)',
    walkIn: 'Venta sin cliente',
    paymentMethod: 'Metodo de Pago',
    notes: 'Notas',
    saleCreated: 'Venta registrada',
    noSales: 'Sin ventas de productos',
    todaySales: 'Ventas de Hoy',
    totalSales: 'Total Vendido',
    items: 'productos',
  },

  // Expense Tracking
  expenses: {
    title: 'Gastos',
    add: '+ Nuevo Gasto',
    create: 'Registrar Gasto',
    category: 'Categoria',
    description: 'Descripcion',
    amount: 'Monto',
    date: 'Fecha',
    recurring: 'Recurrente',
    recurrenceMonthly: 'Mensual',
    recurrenceWeekly: 'Semanal',
    paidTo: 'Pagado a',
    paymentMethod: 'Metodo de Pago',
    noExpenses: 'Sin gastos registrados',
    created: 'Gasto registrado',
    updated: 'Gasto actualizado',
    deleted: 'Gasto eliminado',
    editExpense: 'Editar Gasto',
    deleteConfirm: 'Eliminar este gasto?',
    totalExpenses: 'Total Gastos',
    // Categories
    catRent: 'Alquiler',
    catUtilities: 'Servicios (luz, agua, etc.)',
    catSalaries: 'Salarios',
    catSupplies: 'Insumos',
    catMarketing: 'Marketing',
    catMaintenance: 'Mantenimiento',
    catInsurance: 'Seguro',
    catOther: 'Otro',
    filterByMonth: 'Filtrar por mes',
    thisMonth: 'Este Mes',
    last7Days: 'Últimos 7 días',
    from: 'Desde',
    to: 'Hasta',
  },

  // Loyalty Program
  loyalty: {
    title: 'Programa de Lealtad',
    points: 'Puntos',
    pointsBalance: 'Puntos Disponibles',
    earnRate: '1 punto por cada Bs. 50',
    earned: 'Ganados',
    redeemed: 'Canjeados',
    redeem: 'Canjear',
    redeemReward: 'Canjear Recompensa',
    redeemConfirm: 'Canjear esta recompensa?',
    redeemed2: 'Recompensa canjeada',
    redeemedCredit: 'Recompensa canjeada — saldo agregado',
    redeemedDiscount: 'Descuento registrado — aplicar manualmente en el cobro',
    insufficientPoints: 'Puntos insuficientes',
    history: 'Historial de Puntos',
    noHistory: 'Sin movimientos de puntos',
    rewards: 'Recompensas',
    addReward: '+ Nueva Recompensa',
    editReward: 'Editar Recompensa',
    rewardName: 'Nombre',
    rewardDescription: 'Descripcion',
    pointsCost: 'Costo en Puntos',
    rewardType: 'Tipo',
    rewardValue: 'Valor',
    typeDiscount: 'Descuento %',
    typeFreeService: 'Servicio Gratis',
    typeFreeProduct: 'Producto Gratis',
    typeCredit: 'Saldo a Favor',
    noRewards: 'Sin recompensas configuradas',
    rewardCreated: 'Recompensa creada',
    rewardUpdated: 'Recompensa actualizada',
    rewardDeleted: 'Recompensa eliminada',
    deleteRewardConfirm: 'Eliminar esta recompensa?',
    manageRewards: 'Gestionar Recompensas',
  },
};

export default ES;
